version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://root:edi2025@postgres:5432/edicondominio
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - edicondominio
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: db-condominio
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: edi2025
      POSTGRES_DB: edicondominio
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - edicondominio

  frontend:
    build:
      context: ./../frontend-condominio
      dockerfile: Dockerfile
    volumes:
      - frontend_dist:/app/dist
    networks:
      - edicondominio

  nginx:
    image: nginx:latest
    container_name: nginx-condominio
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - frontend_dist:/usr/share/nginx/html
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - edicondominio

  certbot:
    image: certbot/certbot
    container_name: certbot-condominio
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
    networks:
      - edicondominio

volumes:
  db_data: {}
  frontend_dist: {}

networks:
  edicondominio:
    driver: bridge
