version: '3.8'
services:

  postgres:
    image: postgres:13
    container_name: db-condominio
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: edi2025
      POSTGRES_DB: edicondominio
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - condominio

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3001
  #     - DATABASE_URL=${DATABASE_URL}
  #     - JWT_SECRET=${JWT_SECRET}
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   networks:
  #     - condominio

  # nginx:
  #   image: nginx
  #   container_name: nginx-condominio
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #     - ./:/usr/share/nginx/html
  #   ports:
  #     - "3333:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - condominio

volumes:
  db_data: {}
networks:
  condominio:
    driver: bridge
