version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - edicondominio
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: db-condominio
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: edi2025
      POSTGRES_DB: edicondominio
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - edicondominio

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - edicondominio

  nginx:
    image: nginx
    container_name: nginx-condominio
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - edicondominio

volumes:
  db_data: {}

networks:
  edicondominio:
    driver: bridge
